name: Generar WordCloud Diario

on:
  schedule:
    - cron: '15 16 * * *' 
  workflow_dispatch:  

jobs:
  generate_wordcloud:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Git
      run: |
        git config --global user.email "gaspargomez2000@outlook.com"
        git config --global user.name "ggomez0"

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Puedes especificar la versión que desees

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Instalar dependencias
      run: |
        pip install -r .github/requirements.txt

    - name: Instalar nltk
      run: |
        python mynltk.py

    - name: Ejecutar tarea de generación de WordCloud
      run: |
        python wordcloudgenerator.py

    - name: Subir WordCloud generada
      run: |
        git checkout main
        git add .
        git commit -m "WordCloud generado diario"
        git push origin main
